/**
 * Demo Data Fixtures for the Standalone Product Landing Page & Mini Operator Console.
 * Fully decoupled from backend for instant zero-latency simulation.
 */

import type {
  Health,
  RunListItem,
  RunTimeline,
  ChaosReport,
  ToolDescriptor,
  Worker,
  RunEvent,
} from "./types";

export const DEMO_HEALTH: Health = {
  database_reachable: true,
  redis_reachable: true,
  worker_count: 3,
  healthy_worker_count: 3,
  stale_worker_count: 0,
  pending_run_count: 0,
  running_run_count: 1,
  global_concurrency_cap: 50,
  oldest_pending_age_ms: null,
  deployment_mode: "local",
  active_profile: "demo",
  code_version: "v1.4.9-prod",
  schema_revision: "005_chaos",
  degraded: false,
};

export const DEMO_WORKERS: Worker[] = [
  {
    id: "worker-a#1",
    label: "worker-a",
    incarnation: 1,
    hostname: "anchor-worker-a",
    pid: 4821,
    started_at: new Date(Date.now() - 3600000).toISOString(),
    last_seen_at: new Date().toISOString(),
    heartbeat_age_ms: 180,
    stale: false,
    uptime_ms: 3600000,
    current_run_count: 2,
    capacity: 10,
    steps_executed: 242,
    code_version: "v1.4.9-prod",
    role: "runner",
  },
  {
    id: "worker-b#1",
    label: "worker-b",
    incarnation: 1,
    hostname: "anchor-worker-b",
    pid: 4822,
    started_at: new Date(Date.now() - 3600000).toISOString(),
    last_seen_at: new Date().toISOString(),
    heartbeat_age_ms: 210,
    stale: false,
    uptime_ms: 3600000,
    current_run_count: 1,
    capacity: 10,
    steps_executed: 198,
    code_version: "v1.4.9-prod",
    role: "runner",
  },
  {
    id: "worker-c#1",
    label: "worker-c",
    incarnation: 1,
    hostname: "anchor-worker-c",
    pid: 4823,
    started_at: new Date(Date.now() - 3600000).toISOString(),
    last_seen_at: new Date().toISOString(),
    heartbeat_age_ms: 140,
    stale: false,
    uptime_ms: 3600000,
    current_run_count: 1,
    capacity: 10,
    steps_executed: 315,
    code_version: "v1.4.9-prod",
    role: "runner",
  },
  {
    id: "worker-d#1",
    label: "worker-d",
    incarnation: 1,
    hostname: "anchor-worker-d",
    pid: 4824,
    started_at: new Date(Date.now() - 3600000).toISOString(),
    last_seen_at: new Date().toISOString(),
    heartbeat_age_ms: 290,
    stale: false,
    uptime_ms: 3600000,
    current_run_count: 0,
    capacity: 10,
    steps_executed: 176,
    code_version: "v1.4.9-prod",
    role: "runner",
  },
  {
    id: "worker-e#1",
    label: "worker-e",
    incarnation: 1,
    hostname: "anchor-worker-e",
    pid: 4825,
    started_at: new Date(Date.now() - 3600000).toISOString(),
    last_seen_at: new Date().toISOString(),
    heartbeat_age_ms: 160,
    stale: false,
    uptime_ms: 3600000,
    current_run_count: 1,
    capacity: 10,
    steps_executed: 142,
    code_version: "v1.4.9-prod",
    role: "runner",
  },
];

export const DEMO_RUN_TIMELINE_CRASHED: RunTimeline = {
  id: 101,
  display_id: "r101",
  agent_type: "document_review_agent",
  status: "running",
  started_at: new Date(Date.now() - 14000).toISOString(),
  step_count: 4,
  orphaned: false,
  lease_expires_at: new Date(Date.now() + 8000).toISOString(),
  segments: [
    {
      worker_id: "worker-a#1",
      epoch: 1,
      claim_reason: "initial",
      started_at: new Date(Date.now() - 14000).toISOString(),
      ended_at: new Date(Date.now() - 6000).toISOString(),
      steps: [
        {
          step_index: 0,
          name: "initialize_eval_sandbox",
          status: "done",
          action_kind: "tool",
          started_at: new Date(Date.now() - 14000).toISOString(),
          completed_at: new Date(Date.now() - 13200).toISOString(),
          duration_ms: 800,
          idempotency_key: "r101:s0:init:a1b2",
          idempotency_key_display: "a1b2c3d4",
          executed: true,
        },
        {
          step_index: 1,
          name: "analyze_user_requirements",
          status: "done",
          action_kind: "model",
          started_at: new Date(Date.now() - 12800).toISOString(),
          completed_at: new Date(Date.now() - 12000).toISOString(),
          duration_ms: 800,
          idempotency_key: "r101:s1:analyze:e5f6",
          idempotency_key_display: "e5f6g7h8",
          executed: true,
        },
      ],
      log: [
        { timestamp: new Date(Date.now() - 14000).toISOString(), text: "Claimed run r101 (epoch 1)", level: "info" },
        { timestamp: new Date(Date.now() - 13200).toISOString(), text: "Step 0 (Tool Call) complete: initialize_eval_sandbox", level: "success" },
        { timestamp: new Date(Date.now() - 12000).toISOString(), text: "Step 1 (LLM Model) complete: analyze_user_requirements", level: "success" },
        { timestamp: new Date(Date.now() - 11000).toISOString(), text: "Step 2 (Tool Call) intent recorded: execute_db_migration", level: "info" },
        { timestamp: new Date(Date.now() - 6000).toISOString(), text: "⚡ WORKER CRASH: worker-a#1 process terminated via SIGKILL mid-execution after TOOL_INTENT", level: "warning" },
      ],
    },
    {
      worker_id: "worker-b#1",
      epoch: 2,
      claim_reason: "reclaimed_after_lease_expiry",
      started_at: new Date(Date.now() - 5000).toISOString(),
      ended_at: null,
      steps: [
        {
          step_index: 2,
          name: "execute_db_migration",
          status: "done",
          action_kind: "tool",
          started_at: new Date(Date.now() - 4000).toISOString(),
          completed_at: new Date(Date.now() - 2100).toISOString(),
          duration_ms: 1900,
          idempotency_key: "r101:s2:migrate:i9j0",
          idempotency_key_display: "i9j0k1l2",
          executed: true,
        },
        {
          step_index: 3,
          name: "synthesize_llm_final_response",
          status: "done",
          action_kind: "model",
          started_at: new Date(Date.now() - 2000).toISOString(),
          completed_at: new Date(Date.now() - 500).toISOString(),
          duration_ms: 1500,
          idempotency_key: "r101:s3:synth:m3n4",
          idempotency_key_display: "m3n4o5p6",
          executed: true,
        },
      ],
      log: [
        { timestamp: new Date(Date.now() - 5000).toISOString(), text: "Reclaimed run r101 (epoch 2) via worker-b#1", level: "info" },
        { timestamp: new Date(Date.now() - 2100).toISOString(), text: "Step 2 (Tool Call) picked up from intent: executed & TOOL_RESULT recorded", level: "success" },
        { timestamp: new Date(Date.now() - 500).toISOString(), text: "Step 3 (LLM Model) complete: synthesize_llm_final_response", level: "success" },
      ],
    },
  ],
  fencing_events: [
    {
      at: new Date(Date.now() - 5000).toISOString(),
      fenced_worker_id: "worker-a#1",
      stale_epoch: 1,
      current_epoch: 2,
    },
  ],
  summary: {
    duplicate_side_effects: 0,
    handoff_count: 1,
    recovery_seconds: 3.1,
    effects_executed: 3,
    replayed_step_count: 2,
  },
};

export const DEMO_RUNS_LIST: RunListItem[] = [
  {
    id: 101,
    display_id: "r101",
    agent_type: "document_review_agent",
    status: "running",
    epoch: 2,
    owner_worker_id: "worker-b#1",
    lease_expires_at: new Date(Date.now() + 8000).toISOString(),
    orphaned: false,
    current_step_index: 3,
    step_count: 4,
    attempts: 1,
    priority: 10,
    is_demo: true,
    cancel_requested_at: null,
    created_at: new Date(Date.now() - 14000).toISOString(),
    claimed_at: new Date(Date.now() - 5000).toISOString(),
    finished_at: null,
    elapsed_ms: 14000,
    segments: DEMO_RUN_TIMELINE_CRASHED.segments,
    summary: DEMO_RUN_TIMELINE_CRASHED.summary,
  },
  {
    id: 102,
    display_id: "r102",
    agent_type: "system_verification_agent",
    status: "completed",
    epoch: 1,
    owner_worker_id: null,
    lease_expires_at: null,
    orphaned: false,
    current_step_index: 5,
    step_count: 5,
    attempts: 1,
    priority: 5,
    is_demo: true,
    cancel_requested_at: null,
    created_at: new Date(Date.now() - 120000).toISOString(),
    claimed_at: new Date(Date.now() - 120000).toISOString(),
    finished_at: new Date(Date.now() - 95000).toISOString(),
    elapsed_ms: 25000,
    segments: [
      {
        worker_id: "worker-a#1",
        epoch: 1,
        started_at: new Date(Date.now() - 120000).toISOString(),
        ended_at: new Date(Date.now() - 95000).toISOString(),
        steps: [
          {
            step_index: 0,
            name: "fetch_repo_metadata",
            status: "done",
            action_kind: "tool",
            started_at: new Date(Date.now() - 120000).toISOString(),
            completed_at: new Date(Date.now() - 118000).toISOString(),
            executed: true,
          },
          {
            step_index: 1,
            name: "analyze_ast_complexity",
            status: "done",
            action_kind: "model",
            started_at: new Date(Date.now() - 117500).toISOString(),
            completed_at: new Date(Date.now() - 100000).toISOString(),
            executed: true,
          },
          {
            step_index: 2,
            name: "generate_audit_report",
            status: "done",
            action_kind: "done",
            started_at: new Date(Date.now() - 99000).toISOString(),
            completed_at: new Date(Date.now() - 95000).toISOString(),
            executed: true,
          },
        ],
      },
    ],
    summary: {
      duplicate_side_effects: 0,
      handoff_count: 0,
      recovery_seconds: null,
      effects_executed: 3,
      replayed_step_count: 0,
    },
  },
];

export const DEMO_CHAOS_REPORT: ChaosReport = {
  chaos_run_id: 42,
  invariants: {
    no_duplicate_effects: true,
    log_monotonic: true,
    single_writer_per_epoch: true,
    terminal_reachability: true,
    replay_determinism: true,
  },
  violations: [],
  duplicate_effect_count: 0,
  stranded_run_count: 0,
  kills_injected: 4,
  runs_total: 15,
  steps_total: 45,
  recovery_ms: { p50: 3100, p95: 4200, p99: 4800, max: 5100 },
  replay_steps_mean: 2.2,
  replay_ms_mean: 18.4,
  steps_per_second: 2.4,
  fencing_events: 4,
  uncertainty_entries: { retry_safe: 3, reconcilable: 1, unsafe: 0 },
  dead_letter_count: 0,
  duration_seconds: 240,
  config_profile: "demo",
  lease_duration_ms: 10000,
  created_at: new Date().toISOString(),
};

export const DEMO_TOOLS: ToolDescriptor[] = [
  {
    name: "initialize_eval_sandbox",
    safety: "retry_safe",
    naturally_idempotent: true,
    provider_accepts_key: true,
    has_reconcile_fn: false,
    default_policy: "retry_safe",
    declaration_hash: "hash_init_v1",
    executable: true,
    description: "Spawns an isolated document verification container.",
    last_used_at: new Date().toISOString(),
  },
  {
    name: "compile_submitted_document",
    safety: "retry_safe",
    naturally_idempotent: true,
    provider_accepts_key: false,
    has_reconcile_fn: false,
    default_policy: "retry_safe",
    declaration_hash: "hash_compile_v1",
    executable: true,
    description: "Compiles the submitted document with strict flags.",
    last_used_at: new Date().toISOString(),
  },
  {
    name: "run_unit_test_suite",
    safety: "reconcilable",
    naturally_idempotent: false,
    provider_accepts_key: true,
    has_reconcile_fn: true,
    default_policy: "reconcilable",
    declaration_hash: "hash_test_v1",
    executable: true,
    description: "Executes test runner and reconciles test log against DB idempotency key.",
    last_used_at: new Date().toISOString(),
  },
  {
    name: "send_processing_result_email",
    safety: "unsafe",
    naturally_idempotent: false,
    provider_accepts_key: false,
    has_reconcile_fn: false,
    default_policy: "unsafe",
    declaration_hash: "hash_email_v1",
    executable: true,
    description: "Dispatches customer completion notification email.",
    last_used_at: new Date().toISOString(),
  },
];

export const DEMO_EVENTS: RunEvent[] = [
  {
    run_id: 101,
    seq: 1,
    type: "RUN_SUBMITTED",
    payload: { agent_type: "document_review_agent", priority: 10 },
    epoch: 0,
    worker_id: "api",
    step_index: null,
    created_at: new Date(Date.now() - 14000).toISOString(),
  },
  {
    run_id: 101,
    seq: 2,
    type: "RUN_CLAIMED",
    payload: { worker_id: "worker-a#1", epoch: 1 },
    epoch: 1,
    worker_id: "worker-a#1",
    step_index: null,
    created_at: new Date(Date.now() - 14000).toISOString(),
  },
  {
    run_id: 101,
    seq: 3,
    type: "LLM_CALLED",
    payload: { model: "claude-3-5-sonnet", prompt: "analyze_user_requirements", duration_ms: 800 },
    epoch: 1,
    worker_id: "worker-a#1",
    step_index: 0,
    created_at: new Date(Date.now() - 13900).toISOString(),
  },
  {
    run_id: 101,
    seq: 4,
    type: "STEP_COMPLETED",
    payload: { step_index: 0, name: "analyze_user_requirements", action_kind: "model" },
    epoch: 1,
    worker_id: "worker-a#1",
    step_index: 0,
    created_at: new Date(Date.now() - 13200).toISOString(),
  },
  {
    run_id: 101,
    seq: 5,
    type: "TOOL_INTENT",
    payload: { tool_name: "execute_db_migration", idempotency_key: "r101:s1:migrate:e5f6" },
    epoch: 1,
    worker_id: "worker-a#1",
    step_index: 1,
    created_at: new Date(Date.now() - 13100).toISOString(),
  },
  {
    run_id: 101,
    seq: 6,
    type: "TOOL_RESULT",
    payload: { tool_name: "execute_db_migration", result: { status: "applied", migration_id: "005_chaos" } },
    epoch: 1,
    worker_id: "worker-a#1",
    step_index: 1,
    created_at: new Date(Date.now() - 11500).toISOString(),
  },
  {
    run_id: 101,
    seq: 7,
    type: "STEP_COMPLETED",
    payload: { step_index: 1, name: "execute_db_migration", action_kind: "tool" },
    epoch: 1,
    worker_id: "worker-a#1",
    step_index: 1,
    created_at: new Date(Date.now() - 11500).toISOString(),
  },
  {
    run_id: 101,
    seq: 8,
    type: "WORKER_FENCED",
    payload: { fenced_worker_id: "worker-a#1", stale_epoch: 1, current_epoch: 2, reason: "SIGKILL process termination" },
    epoch: 2,
    worker_id: "worker-b#1",
    step_index: null,
    created_at: new Date(Date.now() - 5000).toISOString(),
  },
  {
    run_id: 101,
    seq: 9,
    type: "RUN_CLAIMED",
    payload: { worker_id: "worker-b#1", epoch: 2, reason: "reclaimed_after_lease_expiry" },
    epoch: 2,
    worker_id: "worker-b#1",
    step_index: null,
    created_at: new Date(Date.now() - 5000).toISOString(),
  },
  {
    run_id: 101,
    seq: 10,
    type: "STEP_SKIPPED_ON_REPLAY",
    payload: { step_index: 2, name: "fetch_external_api_payload", action_kind: "tool", cached_result_loaded: true },
    epoch: 2,
    worker_id: "worker-b#1",
    step_index: 2,
    created_at: new Date(Date.now() - 2100).toISOString(),
  },
  {
    run_id: 101,
    seq: 11,
    type: "LLM_CALLED",
    payload: { model: "gpt-4o", prompt: "synthesize_llm_final_response", duration_ms: 1500 },
    epoch: 2,
    worker_id: "worker-b#1",
    step_index: 3,
    created_at: new Date(Date.now() - 500).toISOString(),
  },
  {
    run_id: 101,
    seq: 12,
    type: "STEP_COMPLETED",
    payload: { step_index: 3, name: "synthesize_llm_final_response", action_kind: "model" },
    epoch: 2,
    worker_id: "worker-b#1",
    step_index: 3,
    created_at: new Date(Date.now() - 500).toISOString(),
  },
];
